// Generated by gencpp from file demo_pkg/RobotStatus.msg
// DO NOT EDIT!


#ifndef DEMO_PKG_MESSAGE_ROBOTSTATUS_H
#define DEMO_PKG_MESSAGE_ROBOTSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo_pkg
{
template <class ContainerAllocator>
struct RobotStatus_
{
  typedef RobotStatus_<ContainerAllocator> Type;

  RobotStatus_()
    : x(0.0)
    , y(0.0)
    , linear_velocity(0.0)
    , angular_velocity(0.0)
    , status()  {
    }
  RobotStatus_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , linear_velocity(0.0)
    , angular_velocity(0.0)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _linear_velocity_type;
  _linear_velocity_type linear_velocity;

   typedef double _angular_velocity_type;
  _angular_velocity_type angular_velocity;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::demo_pkg::RobotStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_pkg::RobotStatus_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStatus_

typedef ::demo_pkg::RobotStatus_<std::allocator<void> > RobotStatus;

typedef boost::shared_ptr< ::demo_pkg::RobotStatus > RobotStatusPtr;
typedef boost::shared_ptr< ::demo_pkg::RobotStatus const> RobotStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_pkg::RobotStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_pkg::RobotStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo_pkg::RobotStatus_<ContainerAllocator1> & lhs, const ::demo_pkg::RobotStatus_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.linear_velocity == rhs.linear_velocity &&
    lhs.angular_velocity == rhs.angular_velocity &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo_pkg::RobotStatus_<ContainerAllocator1> & lhs, const ::demo_pkg::RobotStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo_pkg::RobotStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_pkg::RobotStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_pkg::RobotStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_pkg::RobotStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_pkg::RobotStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_pkg::RobotStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_pkg::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "731353865a9997c772f1aa66b5160356";
  }

  static const char* value(const ::demo_pkg::RobotStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x731353865a9997c7ULL;
  static const uint64_t static_value2 = 0x72f1aa66b5160356ULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_pkg::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_pkg/RobotStatus";
  }

  static const char* value(const ::demo_pkg::RobotStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_pkg::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 linear_velocity\n"
"float64 angular_velocity\n"
"string status\n"
;
  }

  static const char* value(const ::demo_pkg::RobotStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_pkg::RobotStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.linear_velocity);
      stream.next(m.angular_velocity);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_pkg::RobotStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_pkg::RobotStatus_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "linear_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.linear_velocity);
    s << indent << "angular_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.angular_velocity);
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_PKG_MESSAGE_ROBOTSTATUS_H
